### ISSUE TITLE
Cannot initialize checkout form anymore - Illegal character in message header

### ISSUE THREAD

**Issue by bullheadandplato** [iyzico/iyzipay-java#158]
Hello,

As of yesterday everything was working fine, we started receiving following exception
```
Illegal character(s) in message header value: IYZWS <yy>
:<omitted>
com.iyzipay.exception.HttpClientException: Illegal character(s) in message header value: IYZWS <omitted>
:<omitted>
	at com.iyzipay.HttpClient.send(HttpClient.java:88)
	at com.iyzipay.HttpClient.exchange(HttpClient.java:59)
	at com.iyzipay.HttpClient.post(HttpClient.java:43)
	at com.iyzipay.model.CheckoutFormInitialize.create(CheckoutFormInitialize.java:21)
```

We cannot process any payments anymore.

Version: 2.0.127

**Comment by bullheadandplato** [comment]
Closing as problem was on our side.
